// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_Append_Entries_Request    MessageType = 0
	MessageType_Append_Entries_Response   MessageType = 1
	MessageType_Heartbeat_Request         MessageType = 2
	MessageType_Heartbeat_Response        MessageType = 3
	MessageType_Vote_Request              MessageType = 4
	MessageType_Vote_Response             MessageType = 5
	MessageType_Install_Snapshot_Request  MessageType = 6
	MessageType_Install_Snapshot_Response MessageType = 7
)

var MessageType_name = map[int32]string{
	0: "Append_Entries_Request",
	1: "Append_Entries_Response",
	2: "Heartbeat_Request",
	3: "Heartbeat_Response",
	4: "Vote_Request",
	5: "Vote_Response",
	6: "Install_Snapshot_Request",
	7: "Install_Snapshot_Response",
}

var MessageType_value = map[string]int32{
	"Append_Entries_Request":    0,
	"Append_Entries_Response":   1,
	"Heartbeat_Request":         2,
	"Heartbeat_Response":        3,
	"Vote_Request":              4,
	"Vote_Response":             5,
	"Install_Snapshot_Request":  6,
	"Install_Snapshot_Response": 7,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

type Entry struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeartbeatRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Leader               []byte   `protobuf:"bytes,2,opt,name=Leader,proto3" json:"Leader,omitempty"`
	LeaderCommitIndex    uint64   `protobuf:"varint,3,opt,name=LeaderCommitIndex,proto3" json:"LeaderCommitIndex,omitempty"`
	LastLog              uint64   `protobuf:"varint,4,opt,name=LastLog,proto3" json:"LastLog,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,5,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	PrevLogIndex         uint64   `protobuf:"varint,6,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          uint64   `protobuf:"varint,7,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *HeartbeatRequest) GetLeader() []byte {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *HeartbeatRequest) GetLeaderCommitIndex() uint64 {
	if m != nil {
		return m.LeaderCommitIndex
	}
	return 0
}

func (m *HeartbeatRequest) GetLastLog() uint64 {
	if m != nil {
		return m.LastLog
	}
	return 0
}

func (m *HeartbeatRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *HeartbeatRequest) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *HeartbeatRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

type HeartbeatResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type VoteRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,2,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,3,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	PrevLogIndex         uint64   `protobuf:"varint,4,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          uint64   `protobuf:"varint,5,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	Candidate            []byte   `protobuf:"bytes,6,opt,name=Candidate,proto3" json:"Candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (m *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(m, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *VoteRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *VoteRequest) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *VoteRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *VoteRequest) GetCandidate() []byte {
	if m != nil {
		return m.Candidate
	}
	return nil
}

type VoteResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Granted              bool     `protobuf:"varint,2,opt,name=Granted,proto3" json:"Granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{4}
}

func (m *VoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResponse.Unmarshal(m, b)
}
func (m *VoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResponse.Marshal(b, m, deterministic)
}
func (m *VoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResponse.Merge(m, src)
}
func (m *VoteResponse) XXX_Size() int {
	return xxx_messageInfo_VoteResponse.Size(m)
}
func (m *VoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResponse proto.InternalMessageInfo

func (m *VoteResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteResponse) GetGranted() bool {
	if m != nil {
		return m.Granted
	}
	return false
}

type AppendEntriesRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	PrevLogIndex         uint64   `protobuf:"varint,2,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          uint64   `protobuf:"varint,3,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	Leader               []byte   `protobuf:"bytes,4,opt,name=Leader,proto3" json:"Leader,omitempty"`
	LeaderCommitIndex    uint64   `protobuf:"varint,5,opt,name=LeaderCommitIndex,proto3" json:"LeaderCommitIndex,omitempty"`
	Entries              []*Entry `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{5}
}

func (m *AppendEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRequest.Unmarshal(m, b)
}
func (m *AppendEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRequest.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRequest.Merge(m, src)
}
func (m *AppendEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRequest.Size(m)
}
func (m *AppendEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRequest proto.InternalMessageInfo

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeader() []byte {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommitIndex() uint64 {
	if m != nil {
		return m.LeaderCommitIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	NoRetryBackoff       bool     `protobuf:"varint,2,opt,name=NoRetryBackoff,proto3" json:"NoRetryBackoff,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,4,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,5,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{6}
}

func (m *AppendEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResponse.Unmarshal(m, b)
}
func (m *AppendEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResponse.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResponse.Merge(m, src)
}
func (m *AppendEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResponse.Size(m)
}
func (m *AppendEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResponse proto.InternalMessageInfo

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetNoRetryBackoff() bool {
	if m != nil {
		return m.NoRetryBackoff
	}
	return false
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResponse) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *AppendEntriesResponse) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type InstallSnapshotRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Leader               []byte   `protobuf:"bytes,2,opt,name=Leader,proto3" json:"Leader,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,3,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,4,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	Size                 uint64   `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	Conf                 []byte   `protobuf:"bytes,7,opt,name=Conf,proto3" json:"Conf,omitempty"`
	ConfIndex            uint64   `protobuf:"varint,8,opt,name=ConfIndex,proto3" json:"ConfIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotRequest) Reset()         { *m = InstallSnapshotRequest{} }
func (m *InstallSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotRequest) ProtoMessage()    {}
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{7}
}

func (m *InstallSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotRequest.Unmarshal(m, b)
}
func (m *InstallSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotRequest.Merge(m, src)
}
func (m *InstallSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotRequest.Size(m)
}
func (m *InstallSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotRequest proto.InternalMessageInfo

func (m *InstallSnapshotRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLeader() []byte {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *InstallSnapshotRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *InstallSnapshotRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *InstallSnapshotRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InstallSnapshotRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InstallSnapshotRequest) GetConf() []byte {
	if m != nil {
		return m.Conf
	}
	return nil
}

func (m *InstallSnapshotRequest) GetConfIndex() uint64 {
	if m != nil {
		return m.ConfIndex
	}
	return 0
}

type InstallSnapshotResponse struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallSnapshotResponse) Reset()         { *m = InstallSnapshotResponse{} }
func (m *InstallSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*InstallSnapshotResponse) ProtoMessage()    {}
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{8}
}

func (m *InstallSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallSnapshotResponse.Unmarshal(m, b)
}
func (m *InstallSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *InstallSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallSnapshotResponse.Merge(m, src)
}
func (m *InstallSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_InstallSnapshotResponse.Size(m)
}
func (m *InstallSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallSnapshotResponse proto.InternalMessageInfo

func (m *InstallSnapshotResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *InstallSnapshotResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Request struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.MessageType" json:"type,omitempty"`
	Context              []byte      `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{9}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_Append_Entries_Request
}

func (m *Request) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

type Response struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.MessageType" json:"type,omitempty"`
	Context              []byte      `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{10}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_Append_Entries_Request
}

func (m *Response) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func init() {
	proto.RegisterEnum("raftpb.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Entry)(nil), "raftpb.Entry")
	proto.RegisterType((*HeartbeatRequest)(nil), "raftpb.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "raftpb.HeartbeatResponse")
	proto.RegisterType((*VoteRequest)(nil), "raftpb.VoteRequest")
	proto.RegisterType((*VoteResponse)(nil), "raftpb.VoteResponse")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raftpb.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raftpb.AppendEntriesResponse")
	proto.RegisterType((*InstallSnapshotRequest)(nil), "raftpb.InstallSnapshotRequest")
	proto.RegisterType((*InstallSnapshotResponse)(nil), "raftpb.InstallSnapshotResponse")
	proto.RegisterType((*Request)(nil), "raftpb.Request")
	proto.RegisterType((*Response)(nil), "raftpb.Response")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf1, 0x4f, 0xc2, 0xc4, 0xad, 0xd2, 0xa5, 0x4d, 0x0d, 0x14, 0x29, 0xda, 0x03, 0x8d,
	0x10, 0xea, 0xa1, 0x5c, 0xb9, 0x40, 0x41, 0xa5, 0x52, 0x8a, 0xd0, 0x06, 0x21, 0x71, 0x8a, 0x36,
	0xf1, 0x26, 0x44, 0x34, 0x5e, 0x63, 0x6f, 0x51, 0xc3, 0x6b, 0xf1, 0x18, 0x3c, 0x00, 0x47, 0x2e,
	0x9c, 0x79, 0x06, 0xe4, 0xd9, 0x75, 0xe2, 0xc4, 0x69, 0x2c, 0xc1, 0x6d, 0xe6, 0xdb, 0xd9, 0xd9,
	0xf9, 0xc6, 0xdf, 0x8c, 0x01, 0x12, 0x3e, 0x56, 0x27, 0x71, 0x22, 0x95, 0x24, 0x5e, 0x66, 0xc7,
	0x43, 0xfa, 0x11, 0xdc, 0xd7, 0x91, 0x4a, 0xe6, 0x84, 0x80, 0xf3, 0x5e, 0x24, 0xb3, 0xc0, 0xea,
	0x58, 0x5d, 0x87, 0xa1, 0x4d, 0xf6, 0xc1, 0xbd, 0x88, 0x42, 0x71, 0x13, 0xd4, 0x10, 0xd4, 0x0e,
	0x46, 0xce, 0x63, 0x11, 0xd8, 0x1d, 0xab, 0xbb, 0xc3, 0xd0, 0xce, 0xb0, 0x57, 0x5c, 0xf1, 0xc0,
	0xe9, 0x58, 0x5d, 0x9f, 0xa1, 0x4d, 0xff, 0x58, 0xd0, 0x7a, 0x23, 0x78, 0xa2, 0x86, 0x82, 0x2b,
	0x26, 0xbe, 0x5c, 0x8b, 0x54, 0x6d, 0x7c, 0xa6, 0x0d, 0x5e, 0x4f, 0xf0, 0x50, 0x24, 0xf8, 0x8e,
	0xcf, 0x8c, 0x47, 0x9e, 0xc2, 0x9e, 0xb6, 0xce, 0xe4, 0x6c, 0x36, 0x55, 0xba, 0x14, 0x1b, 0x2f,
	0x96, 0x0f, 0x48, 0x00, 0xf5, 0x1e, 0x4f, 0x55, 0x4f, 0x4e, 0xb0, 0x0a, 0x87, 0xe5, 0x2e, 0xe9,
	0x40, 0xd3, 0x98, 0xf8, 0xb4, 0x8b, 0xa7, 0x45, 0x88, 0x50, 0xf0, 0xdf, 0x25, 0xe2, 0x6b, 0x4f,
	0x4e, 0xf4, 0x23, 0x1e, 0x86, 0xac, 0x60, 0x59, 0x16, 0xe3, 0x63, 0x96, 0xba, 0xce, 0x52, 0x80,
	0xe8, 0x31, 0xec, 0x15, 0xf8, 0xa6, 0xb1, 0x8c, 0x52, 0xb1, 0x89, 0x30, 0xfd, 0x61, 0x41, 0xf3,
	0x83, 0x54, 0x62, 0x5b, 0x53, 0x28, 0xf8, 0xa6, 0xc2, 0xe2, 0x27, 0x58, 0xc1, 0xd6, 0x89, 0xd9,
	0xd5, 0xc4, 0x9c, 0x6a, 0x62, 0x6e, 0x89, 0x18, 0x39, 0x82, 0xbb, 0x67, 0x3c, 0x0a, 0xa7, 0x21,
	0x57, 0x02, 0x7b, 0xe3, 0xb3, 0x25, 0x40, 0x9f, 0x83, 0xaf, 0xc9, 0xdc, 0xce, 0x38, 0xfb, 0x38,
	0xe7, 0x09, 0x8f, 0x94, 0x08, 0x91, 0x48, 0x83, 0xe5, 0x2e, 0xfd, 0x65, 0xc1, 0xfe, 0x8b, 0x38,
	0x16, 0x51, 0x98, 0xe9, 0x70, 0x2a, 0xd2, 0x8a, 0xa6, 0xac, 0xd0, 0xa9, 0x55, 0xd3, 0xb1, 0xcb,
	0x74, 0x96, 0x7a, 0x73, 0xaa, 0xf5, 0xe6, 0xde, 0xa6, 0xb7, 0x63, 0xa8, 0x0b, 0x5d, 0x71, 0xe0,
	0x75, 0xec, 0x6e, 0xf3, 0x74, 0xe7, 0x44, 0xcf, 0xd4, 0x09, 0x0e, 0x14, 0xcb, 0x4f, 0xe9, 0x77,
	0x0b, 0x0e, 0xd6, 0x18, 0x6e, 0xe9, 0xd4, 0x63, 0xd8, 0x7d, 0x2b, 0x99, 0x50, 0xc9, 0xfc, 0x25,
	0x1f, 0x7d, 0x96, 0xe3, 0xb1, 0x69, 0xd8, 0x1a, 0x9a, 0x75, 0xb4, 0x7f, 0x3d, 0x1a, 0x89, 0x34,
	0x45, 0x8a, 0x0d, 0x96, 0xbb, 0x25, 0xe5, 0x38, 0xd5, 0xca, 0x29, 0x8f, 0x04, 0xfd, 0x6d, 0x41,
	0xfb, 0x22, 0x4a, 0x15, 0xbf, 0xba, 0xea, 0x47, 0x3c, 0x4e, 0x3f, 0xc9, 0x7f, 0x9a, 0xe1, 0xf5,
	0x62, 0xec, 0xea, 0x62, 0x9c, 0xb2, 0x8c, 0x09, 0x38, 0xfd, 0xe9, 0x37, 0x61, 0xea, 0x44, 0x7b,
	0xb1, 0x72, 0xbc, 0xe5, 0xca, 0xc9, 0xb0, 0x33, 0x19, 0x8d, 0x71, 0x38, 0x7d, 0x86, 0x36, 0x8a,
	0x57, 0x46, 0x63, 0xfd, 0x7c, 0x03, 0x13, 0x2c, 0x01, 0x7a, 0x0e, 0x87, 0x25, 0x96, 0xdb, 0x75,
	0x9c, 0x77, 0xbd, 0xb6, 0xd2, 0x75, 0xda, 0x83, 0x7a, 0xde, 0x9f, 0x63, 0x70, 0x54, 0xb6, 0x20,
	0xb3, 0x8b, 0xbb, 0xa7, 0xf7, 0x72, 0x59, 0x5c, 0x8a, 0x34, 0xe5, 0x13, 0x91, 0xed, 0x4b, 0x86,
	0x01, 0x59, 0xb6, 0x91, 0x8c, 0x94, 0xb8, 0x51, 0xa6, 0x6b, 0xb9, 0x4b, 0x2f, 0xa1, 0xb1, 0xa8,
	0xe3, 0xff, 0xd3, 0x3d, 0xf9, 0x69, 0x41, 0xb3, 0x10, 0x4f, 0x1e, 0x40, 0x5b, 0x2b, 0x72, 0x60,
	0x24, 0x39, 0x30, 0xb5, 0xb7, 0xee, 0x90, 0x87, 0x70, 0x58, 0x3a, 0xd3, 0x95, 0xb4, 0x2c, 0x72,
	0x50, 0x58, 0x71, 0x8b, 0x3b, 0x35, 0xd2, 0x06, 0x52, 0x84, 0x4d, 0xb8, 0x4d, 0x5a, 0x7a, 0x35,
	0x2c, 0x22, 0x1d, 0xb2, 0x07, 0x3b, 0x06, 0x31, 0x41, 0x2e, 0x39, 0x82, 0xc0, 0x7c, 0x82, 0x41,
	0xfe, 0x0d, 0x16, 0x17, 0x3c, 0xf2, 0x08, 0xee, 0x6f, 0x38, 0x35, 0x97, 0xeb, 0x43, 0x0f, 0x7f,
	0x67, 0xcf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x78, 0x9e, 0x40, 0x03, 0xdc, 0x06, 0x00, 0x00,
}
