title = "raft2 config"
loglevel = "debug"

[raft]
id = "raft2"
bind = "127.0.0.1:8002"
nodes = [["raft0", "127.0.0.1:8000"], ["raft1", "127.0.0.1:8001"], ["raft2", "127.0.0.1:8002"]]
is_learner = true

log_store_path = "./raft/2/log_store"
stable_store_path = "./raft/2/stable_store"
snapshot_store_path = "./raft/2/snapshot_store"

heartbeat_timeout = 500
leader_lease_timeout = 250
election_timeout = 1000
commit_timeout = 1000
replicate_timeout = 1000
snapshot_restore_timeout = 60000
snapshot_store_timeout = 60000

snapshot_interval = 5000000
snapshot_threshold = 1000

max_append_logs = 1000

[kvstore]
bind = "0.0.0.0:7002"
path = "./kvstore/2"

[profile]
bind = "0.0.0.0:6002"
